410 backend UI api wrapper get policies endpoint with 02x
sovity/edc-extensions pull request #470
Opened 2023-08-04 16:42 UTC by SaadEGI

Related to  Backend UI API Wrapper: Get Policies Endpoint with 0.2.x #410

2023-08-07 08:46 UTC, richardtreier requested changes

2023-08-07 08:46 UTC, richardtreier commented on extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java
> +    @Path("pages/policy-page")
Nit: Maybe POST pages/policy/page/policies would make more sense, as policies would be the resource, and "pages/policy-page" is just one entry on the resource "pages"

2023-08-07 08:46 UTC, richardtreier commented on extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/UiResource.java
> +    public IdResponse createPolicy(UiPolicyDto policyDto) {
For the createPolicy call we need a UiPolicyCreateDto, which does not contain the legacy policy nor the errors. Meaning we are cutting down the API Model for the create process to what it exactly needs to the behavior will be exactly defined.

The response for this call could actually return a UiPolicyDto, which would make testing easier

2023-08-07 08:46 UTC, richardtreier commented on extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/policy/PolicyApiService.java
> +
newlines

2023-08-07 08:46 UTC, richardtreier commented on extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/policy/PolicyApiService.java
> +        return policies.stream().map(policy -> {
we should have a defined sorting

2023-08-07 08:46 UTC, richardtreier commented on extensions/wrapper/wrapper/src/main/java/de/sovity/edc/ext/wrapper/api/ui/pages/policy/PolicyApiService.java
> +    private List<Policy> getAllPolicies() {
With all the business/product/page naming vs core edc entity naming it is understandable to get confused.

The "policy page" is for managing "policy definitions", meaning, a Policy + Policy Definition ID.

You might have to rework some objects and stuff, as creating a "policy" means creating a "policy definition", which will also require a policy definition ID.

Also the resulting objects will be PolicyDefinitions.

Whether you'll decide to rename your API objects to PolicyDefinitions or not is up to you.

E.g. when fetching another connector's catalog, you get data offers, which contain a policy. At that point you won't have the other connector's internal policy definition's ID. However, when you create a contract definition, the only way you can supply your policy is by specifying a policy definition's ID.

Meaning:
- Policy = Policy JSON-LD, ephermal
- Policy Definition = Persisted Policy + Chosen Policy Definition ID
- Creating a Contract Definition requires a persisted Policy Definition
- Contract Negotiations contain Policies (embedded JSON only, no policy definition ID, as the data offer might come from another connector)
- Contract Offers contain Policies (embedded JSON only, no policy definition ID, the data offers definitely come from other connectors)

2023-08-17 22:39 UTC, closed without merging

2023-08-17 22:40 UTC, SaadEGI commented
duplicate of https://github.com/sovity/edc-extensions/pull/481