feat: log TransferProcess to ClearingHouse
sovity/edc-extensions pull request #58
Opened 2023-01-20 09:50 UTC by tmberthold

Logs a completed TransferProcess to the IDS-ClearingHouse.

2023-01-26 12:19 UTC, efiege requested changes

2023-01-26 12:19 UTC, efiege commented on extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/sender/LogMessageSender.java
> +    private static String buildTransferProcessPayload(TransferProcess transferProcess) {
remove static?

2023-01-26 12:19 UTC, efiege commented on extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/sender/LogMessageSender.java
> +            return null;
Throw an EDCException with a message like "ObjectType {class-name} not support in LogMessageSender"

2023-01-26 12:19 UTC, efiege commented on extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/service/IdsClearingHouseServiceImpl.java
> +            var connectorBaseUrl = getConnectorBaseUrl();
Idea: set in constructor and replace hostname with connectorBaseUrl in the fields

2023-01-26 12:19 UTC, efiege commented on extensions/clearinghouse/src/main/java/de/sovity/extension/clearinghouse/service/IdsClearingHouseServiceImpl.java
> +            var connectorBaseUrl = getConnectorBaseUrl();
The Exception can be caught in the constructor and wrapped in an EDCException. In this way misconfiguration can already be identified on startup

2023-01-30 12:50 UTC, tmberthold commented
EDC can log to CH (copied request into Postman):
![image](https://user-images.githubusercontent.com/75306992/215481593-8866adc3-ea91-4251-9f0f-033d82ba2249.png)

2023-01-30 13:33 UTC, efiege approved these changes

2023-01-30 13:34 UTC, merged